import {
  ArrowDown,
  ArrowRight,
  ArrowsOut,
  BagSimple,
  BellRinging,
  Bone,
  BookOpen,
  Brain,
  Briefcase,
  Buildings,
  Bus,
  CalendarBlank,
  CalendarCheck,
  CalendarDots,
  Car,
  CaretLeft,
  CaretRight,
  CellSignalFull,
  Certificate,
  ChartBar,
  Chat,
  ChatCircleText,
  Chats,
  ChatsCircle,
  CheckCircle,
  CheckSquare,
  ClipboardText,
  Clock,
  CurrencyDollar,
  Desktop,
  DownloadSimple,
  Envelope,
  EnvelopeSimple,
  FileMagnifyingGlass,
  FilePlus,
  FileText,
  Files,
  FirstAid,
  Gavel,
  Globe,
  GraduationCap,
  Handshake,
  Headset,
  Heartbeat,
  House,
  IdentificationCard,
  // Aliased for the same reason as `Link` below: the bare name collides with a
  // global (and with next/image in any file that imports both).
  Image as ImageIcon,
  Info,
  Link as LinkIcon,
  List,
  Lock,
  LockSimple,
  MagnifyingGlass,
  MapPin,
  Medal,
  Monitor,
  NavigationArrow,
  PaperPlaneTilt,
  PersonArmsSpread,
  Phone,
  Pulse,
  Question,
  Scales,
  SealCheck,
  Shield,
  ShieldCheck,
  SignIn,
  Sliders,
  SortAscending,
  SquaresFour,
  Star,
  Stethoscope,
  Target,
  Translate,
  TShirt,
  UploadSimple,
  User,
  UserCheck,
  UserCircle,
  UserPlus,
  Users,
  UsersThree,
  VideoCamera,
  Warning,
  WarningCircle,
  Wheelchair,
  WifiHigh,
  Wind,
} from '@phosphor-icons/react/ssr'
import type { Icon as PhosphorIcon } from '@phosphor-icons/react'
import { cn } from '@/utilities/ui'
import React from 'react'

// Curated icon set, surfaced as a CMS select (see `iconField`). Uses Phosphor
// (duotone) to match the VERIFY design language. Imported from the SSR entry so
// icons render inside React Server Components without a client boundary.
//
// Keys are the STABLE contract shared with seed data and stored content — never
// rename an existing key; add new ones. The `*-simple`/legacy aliases below keep
// older Lucide-era values (mail, scale, search, send, award…) valid.
export const iconMap = {
  // ── Legacy Lucide-era keys (preserved so stored content keeps rendering) ──
  activity: Pulse,
  award: Medal,
  building: Buildings,
  calendar: CalendarDots,
  check: CheckCircle,
  'clipboard-check': ClipboardText,
  'file-text': FileText,
  'heart-pulse': Heartbeat,
  mail: Envelope,
  message: ChatCircleText,
  scale: Scales,
  search: MagnifyingGlass,
  send: PaperPlaneTilt,
  'user-check': UserCheck,
  video: VideoCamera,
  // ── Phosphor names used across the design reference ──
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'arrows-out': ArrowsOut,
  'bag-simple': BagSimple,
  'bell-ringing': BellRinging,
  bone: Bone,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  bus: Bus,
  'calendar-blank': CalendarBlank,
  'calendar-check': CalendarCheck,
  car: Car,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  'cell-signal-full': CellSignalFull,
  certificate: Certificate,
  'chart-bar': ChartBar,
  chat: Chat,
  'chat-circle-text': ChatCircleText,
  chats: Chats,
  'chats-circle': ChatsCircle,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'clipboard-text': ClipboardText,
  clock: Clock,
  'currency-dollar': CurrencyDollar,
  desktop: Desktop,
  download: DownloadSimple,
  'download-simple': DownloadSimple,
  envelope: Envelope,
  'envelope-simple': EnvelopeSimple,
  'file-magnifying-glass': FileMagnifyingGlass,
  'file-plus': FilePlus,
  files: Files,
  'first-aid': FirstAid,
  gavel: Gavel,
  globe: Globe,
  'graduation-cap': GraduationCap,
  handshake: Handshake,
  headset: Headset,
  heartbeat: Heartbeat,
  home: House,
  house: House,
  'identification-card': IdentificationCard,
  image: ImageIcon,
  info: Info,
  link: LinkIcon,
  list: List,
  lock: Lock,
  'lock-simple': LockSimple,
  'magnifying-glass': MagnifyingGlass,
  'map-pin': MapPin,
  medal: Medal,
  monitor: Monitor,
  'navigation-arrow': NavigationArrow,
  'paper-plane-tilt': PaperPlaneTilt,
  'person-arms-spread': PersonArmsSpread,
  phone: Phone,
  question: Question,
  scales: Scales,
  'seal-check': SealCheck,
  shield: Shield,
  'shield-check': ShieldCheck,
  'sign-in': SignIn,
  sliders: Sliders,
  'sort-ascending': SortAscending,
  'squares-four': SquaresFour,
  star: Star,
  stethoscope: Stethoscope,
  target: Target,
  translate: Translate,
  't-shirt': TShirt,
  upload: UploadSimple,
  'upload-simple': UploadSimple,
  user: User,
  'user-circle': UserCircle,
  'user-plus': UserPlus,
  users: Users,
  'users-three': UsersThree,
  'video-camera': VideoCamera,
  warning: Warning,
  'warning-circle': WarningCircle,
  wheelchair: Wheelchair,
  'wifi-high': WifiHigh,
  wind: Wind,
} satisfies Record<string, PhosphorIcon>

export type IconName = keyof typeof iconMap

// Options for a Payload `select` field (kept in sync with the map above).
export const iconOptions = (Object.keys(iconMap) as IconName[])
  .sort()
  .map((value) => ({
    label: value
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' '),
    value,
  }))

export const Icon: React.FC<{
  name?: IconName | string | null
  className?: string
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone'
}> = ({ name, className, weight = 'duotone' }) => {
  if (!name) return null
  const Cmp = iconMap[name as IconName]
  if (!Cmp) return null
  return <Cmp className={cn('size-6', className)} weight={weight} aria-hidden />
}
