import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'

/**
 * Adds every new enum label, OUTSIDE the migration's wrapping transaction.
 *
 * ── Why this is a separate migration, and why it does not use `db` ──────────
 * Payload runs each migration inside a transaction it opens itself:
 * `runMigrationFile` in @payloadcms/drizzle calls `initTransaction(req)`, hands
 * `up()` a transaction-scoped `db`, then commits. There is no
 * `disableTransaction` flag in Payload 3.85 — I checked the runner.
 *
 * Two Postgres rules make that fatal for this change:
 *   · `ALTER TYPE ... ADD VALUE` cannot run inside a transaction block at all on
 *     PostgreSQL before 12; and
 *   · even on 12+, a label added in a transaction cannot be USED until that
 *     transaction commits — which the companion migration does, with
 *     `SET DEFAULT 'hero'`.
 *
 * So these statements go through `payload.db.pool` instead of the `db` argument.
 * That is a different connection from the pool, outside the wrapping
 * transaction, in autocommit — which satisfies both rules on every version.
 *
 * They are issued ONE PER `query()` call deliberately. node-postgres sends a
 * multi-statement string through the simple query protocol, which wraps the lot
 * in a single implicit transaction — reintroducing exactly the problem this file
 * exists to avoid.
 *
 * `IF NOT EXISTS` on every statement makes this re-runnable, so a database that
 * already has some labels (a dev box that was schema-pushed, or a partially
 * applied attempt) converges instead of erroring.
 *
 * The companion `..._editor_controls` migration runs next, in its own
 * transaction, which begins after this one has committed — so the labels are
 * visible to it. Do not merge the two files back together.
 */
const ENUM_ADDITIONS: string[] = [
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_gateway_cards_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_feature_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_process_steps_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_people_grid_header_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_services_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_testimonials_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_stats_band_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_aamle_education_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_split_feature_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_tabs_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_leadership_spotlight_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_video_embed_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_try_booking_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_section_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_archive_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialist_directory_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_specialty_directory_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_resources_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_appt_guide_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_value_cards_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_audience_pathways_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_featured_articles_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_separator_past_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_blocks_events_explorer_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum_pages_hero_hero_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_faq_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_gateway_cards_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_process_steps_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_people_grid_header_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_services_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_testimonials_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_stats_band_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_aamle_education_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_split_feature_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_tabs_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_leadership_spotlight_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_video_embed_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_try_booking_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_section_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_archive_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialist_directory_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_specialty_directory_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_resources_grid_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__appt_guide_v_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_value_cards_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_audience_pathways_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_featured_articles_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'linkblue' BEFORE 'bright'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'definition' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'sky' BEFORE 'muted'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'black' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'charcoal' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'grey' BEFORE 'white'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'success' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'warning' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" ADD VALUE IF NOT EXISTS 'error' BEFORE 'heading'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_separator_past_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_blocks_events_explorer_background" ADD VALUE IF NOT EXISTS 'hero'`,
  `ALTER TYPE "public"."enum__pages_v_version_hero_hero_background" ADD VALUE IF NOT EXISTS 'hero'`,
]

export async function up({ payload }: MigrateUpArgs): Promise<void> {
  const { pool } = payload.db as unknown as { pool: { query: (sql: string) => Promise<unknown> } }
  for (const statement of ENUM_ADDITIONS) {
    await pool.query(statement)
  }
  payload.logger.info(`Added ${ENUM_ADDITIONS.length} enum labels outside the migration transaction`)
}

export async function down(_args: MigrateDownArgs): Promise<void> {
  // Intentionally empty. Postgres cannot remove a label from an enum, and it does
  // not need to here: migrations revert in reverse order, so the companion
  // migration's `down()` runs first and rebuilds every one of these types from
  // scratch with the old label set (cast to text, DROP TYPE, CREATE TYPE, cast
  // back). By the time this runs there is nothing left to undo.
}
