import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// The 540 `ALTER TYPE ... ADD VALUE` statements this migration used to open with
// now live in `20260824_122116_editor_controls_enums`, which runs immediately
// before it. They cannot run inside the transaction Payload wraps around `up()`,
// and `SET DEFAULT 'hero'` below cannot use a label added in the same
// transaction. That file explains both rules; do not fold them back in here.
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TYPE "public"."enum_specialists_profile_photo_shape" AS ENUM('tall', 'portrait', 'square');
  CREATE TYPE "public"."enum__specialists_v_version_profile_photo_shape" AS ENUM('tall', 'portrait', 'square');
  CREATE TYPE "public"."enum_team_profile_photo_shape" AS ENUM('tall', 'portrait', 'square');
  CREATE TYPE "public"."enum__team_v_version_profile_photo_shape" AS ENUM('tall', 'portrait', 'square');
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "background" SET DEFAULT 'hero';
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "background" SET DEFAULT 'hero';
  ALTER TABLE "specialists" ADD COLUMN "profile_photo_shape" "enum_specialists_profile_photo_shape" DEFAULT 'tall';
  ALTER TABLE "_specialists_v" ADD COLUMN "version_profile_photo_shape" "enum__specialists_v_version_profile_photo_shape" DEFAULT 'tall';
  ALTER TABLE "team" ADD COLUMN "profile_photo_shape" "enum_team_profile_photo_shape" DEFAULT 'tall';
  ALTER TABLE "_team_v" ADD COLUMN "version_profile_photo_shape" "enum__team_v_version_profile_photo_shape" DEFAULT 'tall';
  ALTER TABLE "site_settings" ADD COLUMN "colors_ink_black" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "colors_ink_charcoal" varchar;
  ALTER TABLE "site_settings" ADD COLUMN "colors_ink_grey" varchar;
`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_faq" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_faq_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_faq_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_faq_text_colour";
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_faq_text_colour" USING "text_colour"::"public"."enum_pages_blocks_faq_text_colour";
  ALTER TABLE "pages_blocks_gateway_cards" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_gateway_cards" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_gateway_cards_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_gateway_cards" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_gateway_cards_text_colour";
  ALTER TABLE "pages_blocks_gateway_cards" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_gateway_cards_text_colour" USING "text_colour"::"public"."enum_pages_blocks_gateway_cards_text_colour";
  ALTER TABLE "pages_blocks_gateway_cards" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_gateway_cards" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_gateway_cards_background";
  CREATE TYPE "public"."enum_pages_blocks_gateway_cards_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_gateway_cards" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_gateway_cards_background";
  ALTER TABLE "pages_blocks_gateway_cards" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_gateway_cards_background" USING "background"::"public"."enum_pages_blocks_gateway_cards_background";
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_feature_grid_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_feature_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_feature_grid_text_colour";
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_feature_grid_text_colour" USING "text_colour"::"public"."enum_pages_blocks_feature_grid_text_colour";
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_feature_grid_background";
  CREATE TYPE "public"."enum_pages_blocks_feature_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_feature_grid_background";
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_feature_grid_background" USING "background"::"public"."enum_pages_blocks_feature_grid_background";
  ALTER TABLE "pages_blocks_process_steps" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_process_steps" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_process_steps_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_process_steps_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_process_steps" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_process_steps_text_colour";
  ALTER TABLE "pages_blocks_process_steps" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_process_steps_text_colour" USING "text_colour"::"public"."enum_pages_blocks_process_steps_text_colour";
  ALTER TABLE "pages_blocks_process_steps" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_process_steps" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_process_steps_background";
  CREATE TYPE "public"."enum_pages_blocks_process_steps_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_process_steps" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_process_steps_background";
  ALTER TABLE "pages_blocks_process_steps" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_process_steps_background" USING "background"::"public"."enum_pages_blocks_process_steps_background";
  ALTER TABLE "pages_blocks_specialty_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_specialty_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_specialty_grid_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_specialty_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_specialty_grid_text_colour";
  ALTER TABLE "pages_blocks_specialty_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_specialty_grid_text_colour" USING "text_colour"::"public"."enum_pages_blocks_specialty_grid_text_colour";
  ALTER TABLE "pages_blocks_specialty_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_specialty_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_specialty_grid_background";
  CREATE TYPE "public"."enum_pages_blocks_specialty_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_specialty_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_specialty_grid_background";
  ALTER TABLE "pages_blocks_specialty_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_specialty_grid_background" USING "background"::"public"."enum_pages_blocks_specialty_grid_background";
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_people_grid_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_people_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_people_grid_text_colour";
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_people_grid_text_colour" USING "text_colour"::"public"."enum_pages_blocks_people_grid_text_colour";
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_people_grid_background";
  CREATE TYPE "public"."enum_pages_blocks_people_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_people_grid_background";
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_people_grid_background" USING "background"::"public"."enum_pages_blocks_people_grid_background";
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "header_background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "header_background" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_pages_blocks_people_grid_header_background";
  CREATE TYPE "public"."enum_pages_blocks_people_grid_header_background" AS ENUM('default', 'white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "header_background" SET DEFAULT 'default'::"public"."enum_pages_blocks_people_grid_header_background";
  ALTER TABLE "pages_blocks_people_grid" ALTER COLUMN "header_background" SET DATA TYPE "public"."enum_pages_blocks_people_grid_header_background" USING "header_background"::"public"."enum_pages_blocks_people_grid_header_background";
  ALTER TABLE "pages_blocks_services_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_services_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_services_grid_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_services_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_services_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_services_grid_text_colour";
  ALTER TABLE "pages_blocks_services_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_services_grid_text_colour" USING "text_colour"::"public"."enum_pages_blocks_services_grid_text_colour";
  ALTER TABLE "pages_blocks_services_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_services_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_services_grid_background";
  CREATE TYPE "public"."enum_pages_blocks_services_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_services_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_services_grid_background";
  ALTER TABLE "pages_blocks_services_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_services_grid_background" USING "background"::"public"."enum_pages_blocks_services_grid_background";
  ALTER TABLE "pages_blocks_testimonials_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_testimonials_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_testimonials_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_testimonials_grid_text_colour";
  ALTER TABLE "pages_blocks_testimonials_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_testimonials_grid_text_colour" USING "text_colour"::"public"."enum_pages_blocks_testimonials_grid_text_colour";
  ALTER TABLE "pages_blocks_testimonials_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_testimonials_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_testimonials_grid_background";
  CREATE TYPE "public"."enum_pages_blocks_testimonials_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_testimonials_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_testimonials_grid_background";
  ALTER TABLE "pages_blocks_testimonials_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_testimonials_grid_background" USING "background"::"public"."enum_pages_blocks_testimonials_grid_background";
  ALTER TABLE "pages_blocks_stats_band" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_stats_band" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_stats_band_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_stats_band_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_stats_band" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_stats_band_text_colour";
  ALTER TABLE "pages_blocks_stats_band" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_stats_band_text_colour" USING "text_colour"::"public"."enum_pages_blocks_stats_band_text_colour";
  ALTER TABLE "pages_blocks_stats_band" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_stats_band" ALTER COLUMN "background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum_pages_blocks_stats_band_background";
  CREATE TYPE "public"."enum_pages_blocks_stats_band_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_stats_band" ALTER COLUMN "background" SET DEFAULT 'primary'::"public"."enum_pages_blocks_stats_band_background";
  ALTER TABLE "pages_blocks_stats_band" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_stats_band_background" USING "background"::"public"."enum_pages_blocks_stats_band_background";
  ALTER TABLE "pages_blocks_aamle_education" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_aamle_education" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_aamle_education_background";
  CREATE TYPE "public"."enum_pages_blocks_aamle_education_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_aamle_education" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_aamle_education_background";
  ALTER TABLE "pages_blocks_aamle_education" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_aamle_education_background" USING "background"::"public"."enum_pages_blocks_aamle_education_background";
  ALTER TABLE "pages_blocks_split_feature" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_split_feature" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_split_feature_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_split_feature_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_split_feature" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_split_feature_text_colour";
  ALTER TABLE "pages_blocks_split_feature" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_split_feature_text_colour" USING "text_colour"::"public"."enum_pages_blocks_split_feature_text_colour";
  ALTER TABLE "pages_blocks_split_feature" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_split_feature" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_split_feature_background";
  CREATE TYPE "public"."enum_pages_blocks_split_feature_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_split_feature" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_split_feature_background";
  ALTER TABLE "pages_blocks_split_feature" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_split_feature_background" USING "background"::"public"."enum_pages_blocks_split_feature_background";
  ALTER TABLE "pages_blocks_tabs" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_tabs" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_tabs_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_tabs_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_tabs" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_tabs_text_colour";
  ALTER TABLE "pages_blocks_tabs" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_tabs_text_colour" USING "text_colour"::"public"."enum_pages_blocks_tabs_text_colour";
  ALTER TABLE "pages_blocks_tabs" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_tabs" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_tabs_background";
  CREATE TYPE "public"."enum_pages_blocks_tabs_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_tabs" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_tabs_background";
  ALTER TABLE "pages_blocks_tabs" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_tabs_background" USING "background"::"public"."enum_pages_blocks_tabs_background";
  ALTER TABLE "pages_blocks_contact_details" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_contact_details" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_contact_details_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_contact_details_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_contact_details" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_contact_details_text_colour";
  ALTER TABLE "pages_blocks_contact_details" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_contact_details_text_colour" USING "text_colour"::"public"."enum_pages_blocks_contact_details_text_colour";
  ALTER TABLE "pages_blocks_icon_list" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_icon_list" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_icon_list_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_icon_list_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_icon_list" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_icon_list_text_colour";
  ALTER TABLE "pages_blocks_icon_list" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_icon_list_text_colour" USING "text_colour"::"public"."enum_pages_blocks_icon_list_text_colour";
  ALTER TABLE "pages_blocks_map_embed" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_map_embed" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_map_embed_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_map_embed_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_map_embed" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_map_embed_text_colour";
  ALTER TABLE "pages_blocks_map_embed" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_map_embed_text_colour" USING "text_colour"::"public"."enum_pages_blocks_map_embed_text_colour";
  ALTER TABLE "pages_blocks_leadership_spotlight" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_leadership_spotlight" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_leadership_spotlight" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_leadership_spotlight_text_colour";
  ALTER TABLE "pages_blocks_leadership_spotlight" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_leadership_spotlight_text_colour" USING "text_colour"::"public"."enum_pages_blocks_leadership_spotlight_text_colour";
  ALTER TABLE "pages_blocks_leadership_spotlight" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_leadership_spotlight" ALTER COLUMN "background" SET DEFAULT 'muted'::text;
  DROP TYPE "public"."enum_pages_blocks_leadership_spotlight_background";
  CREATE TYPE "public"."enum_pages_blocks_leadership_spotlight_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_leadership_spotlight" ALTER COLUMN "background" SET DEFAULT 'muted'::"public"."enum_pages_blocks_leadership_spotlight_background";
  ALTER TABLE "pages_blocks_leadership_spotlight" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_leadership_spotlight_background" USING "background"::"public"."enum_pages_blocks_leadership_spotlight_background";
  ALTER TABLE "pages_blocks_video_embed" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_video_embed" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_video_embed_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_video_embed_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_video_embed" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_video_embed_text_colour";
  ALTER TABLE "pages_blocks_video_embed" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_video_embed_text_colour" USING "text_colour"::"public"."enum_pages_blocks_video_embed_text_colour";
  ALTER TABLE "pages_blocks_video_embed" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_video_embed" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_video_embed_background";
  CREATE TYPE "public"."enum_pages_blocks_video_embed_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_video_embed" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_video_embed_background";
  ALTER TABLE "pages_blocks_video_embed" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_video_embed_background" USING "background"::"public"."enum_pages_blocks_video_embed_background";
  ALTER TABLE "pages_blocks_try_booking" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_try_booking" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_try_booking_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_try_booking_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_try_booking" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_try_booking_text_colour";
  ALTER TABLE "pages_blocks_try_booking" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_try_booking_text_colour" USING "text_colour"::"public"."enum_pages_blocks_try_booking_text_colour";
  ALTER TABLE "pages_blocks_try_booking" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_try_booking" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_try_booking_background";
  CREATE TYPE "public"."enum_pages_blocks_try_booking_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_try_booking" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_try_booking_background";
  ALTER TABLE "pages_blocks_try_booking" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_try_booking_background" USING "background"::"public"."enum_pages_blocks_try_booking_background";
  ALTER TABLE "pages_blocks_section" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_section" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_section_background";
  CREATE TYPE "public"."enum_pages_blocks_section_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_section" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_section_background";
  ALTER TABLE "pages_blocks_section" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_section_background" USING "background"::"public"."enum_pages_blocks_section_background";
  ALTER TABLE "pages_blocks_archive" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_archive" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_archive_background";
  CREATE TYPE "public"."enum_pages_blocks_archive_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_archive" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_archive_background";
  ALTER TABLE "pages_blocks_archive" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_archive_background" USING "background"::"public"."enum_pages_blocks_archive_background";
  ALTER TABLE "pages_blocks_specialist_directory" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_specialist_directory" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_specialist_directory_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_specialist_directory" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_specialist_directory_text_colour";
  ALTER TABLE "pages_blocks_specialist_directory" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_specialist_directory_text_colour" USING "text_colour"::"public"."enum_pages_blocks_specialist_directory_text_colour";
  ALTER TABLE "pages_blocks_specialist_directory" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_specialist_directory" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_specialist_directory_background";
  CREATE TYPE "public"."enum_pages_blocks_specialist_directory_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_specialist_directory" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_specialist_directory_background";
  ALTER TABLE "pages_blocks_specialist_directory" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_specialist_directory_background" USING "background"::"public"."enum_pages_blocks_specialist_directory_background";
  ALTER TABLE "pages_blocks_specialty_directory" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_specialty_directory" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_specialty_directory_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_specialty_directory" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_specialty_directory_text_colour";
  ALTER TABLE "pages_blocks_specialty_directory" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_specialty_directory_text_colour" USING "text_colour"::"public"."enum_pages_blocks_specialty_directory_text_colour";
  ALTER TABLE "pages_blocks_specialty_directory" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_specialty_directory" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_specialty_directory_background";
  CREATE TYPE "public"."enum_pages_blocks_specialty_directory_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_specialty_directory" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_specialty_directory_background";
  ALTER TABLE "pages_blocks_specialty_directory" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_specialty_directory_background" USING "background"::"public"."enum_pages_blocks_specialty_directory_background";
  ALTER TABLE "pages_blocks_resources_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_resources_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_resources_grid_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_resources_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_resources_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_resources_grid_text_colour";
  ALTER TABLE "pages_blocks_resources_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_resources_grid_text_colour" USING "text_colour"::"public"."enum_pages_blocks_resources_grid_text_colour";
  ALTER TABLE "pages_blocks_resources_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_resources_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_resources_grid_background";
  CREATE TYPE "public"."enum_pages_blocks_resources_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_resources_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_resources_grid_background";
  ALTER TABLE "pages_blocks_resources_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_resources_grid_background" USING "background"::"public"."enum_pages_blocks_resources_grid_background";
  ALTER TABLE "appt_guide" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "appt_guide" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_appt_guide_text_colour";
  CREATE TYPE "public"."enum_appt_guide_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "appt_guide" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_appt_guide_text_colour";
  ALTER TABLE "appt_guide" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_appt_guide_text_colour" USING "text_colour"::"public"."enum_appt_guide_text_colour";
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "background" SET DEFAULT 'dark'::text;
  DROP TYPE "public"."enum_pages_blocks_mission_pillars_background";
  CREATE TYPE "public"."enum_pages_blocks_mission_pillars_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "background" SET DEFAULT 'dark'::"public"."enum_pages_blocks_mission_pillars_background";
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_mission_pillars_background" USING "background"::"public"."enum_pages_blocks_mission_pillars_background";
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_mission_pillars_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_mission_pillars_text_colour";
  ALTER TABLE "pages_blocks_mission_pillars" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_mission_pillars_text_colour" USING "text_colour"::"public"."enum_pages_blocks_mission_pillars_text_colour";
  ALTER TABLE "pages_blocks_value_cards" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_value_cards" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_value_cards_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_value_cards_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_value_cards" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_value_cards_text_colour";
  ALTER TABLE "pages_blocks_value_cards" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_value_cards_text_colour" USING "text_colour"::"public"."enum_pages_blocks_value_cards_text_colour";
  ALTER TABLE "pages_blocks_value_cards" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_value_cards" ALTER COLUMN "background" SET DEFAULT 'dark'::text;
  DROP TYPE "public"."enum_pages_blocks_value_cards_background";
  CREATE TYPE "public"."enum_pages_blocks_value_cards_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_value_cards" ALTER COLUMN "background" SET DEFAULT 'dark'::"public"."enum_pages_blocks_value_cards_background";
  ALTER TABLE "pages_blocks_value_cards" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_value_cards_background" USING "background"::"public"."enum_pages_blocks_value_cards_background";
  ALTER TABLE "pages_blocks_why_verify" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_why_verify" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_why_verify_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_why_verify_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_why_verify" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_why_verify_text_colour";
  ALTER TABLE "pages_blocks_why_verify" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_why_verify_text_colour" USING "text_colour"::"public"."enum_pages_blocks_why_verify_text_colour";
  ALTER TABLE "pages_blocks_audience_pathways" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_audience_pathways" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_audience_pathways_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_audience_pathways" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_audience_pathways_text_colour";
  ALTER TABLE "pages_blocks_audience_pathways" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_audience_pathways_text_colour" USING "text_colour"::"public"."enum_pages_blocks_audience_pathways_text_colour";
  ALTER TABLE "pages_blocks_audience_pathways" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_audience_pathways" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_audience_pathways_background";
  CREATE TYPE "public"."enum_pages_blocks_audience_pathways_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_audience_pathways" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_audience_pathways_background";
  ALTER TABLE "pages_blocks_audience_pathways" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_audience_pathways_background" USING "background"::"public"."enum_pages_blocks_audience_pathways_background";
  ALTER TABLE "pages_blocks_cost_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cost_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_cost_grid_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_cost_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_cost_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_cost_grid_text_colour";
  ALTER TABLE "pages_blocks_cost_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_cost_grid_text_colour" USING "text_colour"::"public"."enum_pages_blocks_cost_grid_text_colour";
  ALTER TABLE "pages_blocks_featured_articles" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_featured_articles" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_featured_articles_background";
  CREATE TYPE "public"."enum_pages_blocks_featured_articles_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_featured_articles" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_featured_articles_background";
  ALTER TABLE "pages_blocks_featured_articles" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_featured_articles_background" USING "background"::"public"."enum_pages_blocks_featured_articles_background";
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum_pages_blocks_events_explorer_text_colour";
  CREATE TYPE "public"."enum_pages_blocks_events_explorer_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum_pages_blocks_events_explorer_text_colour";
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum_pages_blocks_events_explorer_text_colour" USING "text_colour"::"public"."enum_pages_blocks_events_explorer_text_colour";
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "separator_past_background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "separator_past_background" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_pages_blocks_events_explorer_separator_past_background";
  CREATE TYPE "public"."enum_pages_blocks_events_explorer_separator_past_background" AS ENUM('default', 'white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "separator_past_background" SET DEFAULT 'default'::"public"."enum_pages_blocks_events_explorer_separator_past_background";
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "separator_past_background" SET DATA TYPE "public"."enum_pages_blocks_events_explorer_separator_past_background" USING "separator_past_background"::"public"."enum_pages_blocks_events_explorer_separator_past_background";
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum_pages_blocks_events_explorer_background";
  CREATE TYPE "public"."enum_pages_blocks_events_explorer_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum_pages_blocks_events_explorer_background";
  ALTER TABLE "pages_blocks_events_explorer" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_events_explorer_background" USING "background"::"public"."enum_pages_blocks_events_explorer_background";
  ALTER TABLE "pages" ALTER COLUMN "hero_hero_background" SET DATA TYPE text;
  ALTER TABLE "pages" ALTER COLUMN "hero_hero_background" SET DEFAULT 'accent-solid'::text;
  DROP TYPE "public"."enum_pages_hero_hero_background";
  CREATE TYPE "public"."enum_pages_hero_hero_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "pages" ALTER COLUMN "hero_hero_background" SET DEFAULT 'accent-solid'::"public"."enum_pages_hero_hero_background";
  ALTER TABLE "pages" ALTER COLUMN "hero_hero_background" SET DATA TYPE "public"."enum_pages_hero_hero_background" USING "hero_hero_background"::"public"."enum_pages_hero_hero_background";
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_faq_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_faq_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_faq_text_colour";
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_faq_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_faq_text_colour";
  ALTER TABLE "_pages_v_blocks_gateway_cards" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_gateway_cards" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_gateway_cards" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_gateway_cards_text_colour";
  ALTER TABLE "_pages_v_blocks_gateway_cards" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_gateway_cards_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_gateway_cards_text_colour";
  ALTER TABLE "_pages_v_blocks_gateway_cards" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_gateway_cards" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_gateway_cards_background";
  CREATE TYPE "public"."enum__pages_v_blocks_gateway_cards_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_gateway_cards" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_gateway_cards_background";
  ALTER TABLE "_pages_v_blocks_gateway_cards" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_gateway_cards_background" USING "background"::"public"."enum__pages_v_blocks_gateway_cards_background";
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_feature_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_feature_grid_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_feature_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_feature_grid_background";
  CREATE TYPE "public"."enum__pages_v_blocks_feature_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_feature_grid_background";
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_feature_grid_background" USING "background"::"public"."enum__pages_v_blocks_feature_grid_background";
  ALTER TABLE "_pages_v_blocks_process_steps" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_process_steps" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_process_steps_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_process_steps" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_process_steps_text_colour";
  ALTER TABLE "_pages_v_blocks_process_steps" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_process_steps_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_process_steps_text_colour";
  ALTER TABLE "_pages_v_blocks_process_steps" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_process_steps" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_process_steps_background";
  CREATE TYPE "public"."enum__pages_v_blocks_process_steps_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_process_steps" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_process_steps_background";
  ALTER TABLE "_pages_v_blocks_process_steps" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_process_steps_background" USING "background"::"public"."enum__pages_v_blocks_process_steps_background";
  ALTER TABLE "_pages_v_blocks_specialty_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_specialty_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_specialty_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_specialty_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_specialty_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_specialty_grid_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_specialty_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_specialty_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_specialty_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_specialty_grid_background";
  CREATE TYPE "public"."enum__pages_v_blocks_specialty_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_specialty_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_specialty_grid_background";
  ALTER TABLE "_pages_v_blocks_specialty_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_specialty_grid_background" USING "background"::"public"."enum__pages_v_blocks_specialty_grid_background";
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_people_grid_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_people_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_people_grid_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_people_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_people_grid_background";
  CREATE TYPE "public"."enum__pages_v_blocks_people_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_people_grid_background";
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_people_grid_background" USING "background"::"public"."enum__pages_v_blocks_people_grid_background";
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "header_background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "header_background" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum__pages_v_blocks_people_grid_header_background";
  CREATE TYPE "public"."enum__pages_v_blocks_people_grid_header_background" AS ENUM('default', 'white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "header_background" SET DEFAULT 'default'::"public"."enum__pages_v_blocks_people_grid_header_background";
  ALTER TABLE "_pages_v_blocks_people_grid" ALTER COLUMN "header_background" SET DATA TYPE "public"."enum__pages_v_blocks_people_grid_header_background" USING "header_background"::"public"."enum__pages_v_blocks_people_grid_header_background";
  ALTER TABLE "_pages_v_blocks_services_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_services_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_services_grid_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_services_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_services_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_services_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_services_grid_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_services_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_services_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_services_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_services_grid_background";
  CREATE TYPE "public"."enum__pages_v_blocks_services_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_services_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_services_grid_background";
  ALTER TABLE "_pages_v_blocks_services_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_services_grid_background" USING "background"::"public"."enum__pages_v_blocks_services_grid_background";
  ALTER TABLE "_pages_v_blocks_testimonials_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_testimonials_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_testimonials_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_testimonials_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_testimonials_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_testimonials_grid_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_testimonials_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_testimonials_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_testimonials_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_grid_background";
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_testimonials_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_testimonials_grid_background";
  ALTER TABLE "_pages_v_blocks_testimonials_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_testimonials_grid_background" USING "background"::"public"."enum__pages_v_blocks_testimonials_grid_background";
  ALTER TABLE "_pages_v_blocks_stats_band" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_stats_band" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_stats_band_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_stats_band" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_stats_band_text_colour";
  ALTER TABLE "_pages_v_blocks_stats_band" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_stats_band_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_stats_band_text_colour";
  ALTER TABLE "_pages_v_blocks_stats_band" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_stats_band" ALTER COLUMN "background" SET DEFAULT 'primary'::text;
  DROP TYPE "public"."enum__pages_v_blocks_stats_band_background";
  CREATE TYPE "public"."enum__pages_v_blocks_stats_band_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_stats_band" ALTER COLUMN "background" SET DEFAULT 'primary'::"public"."enum__pages_v_blocks_stats_band_background";
  ALTER TABLE "_pages_v_blocks_stats_band" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_stats_band_background" USING "background"::"public"."enum__pages_v_blocks_stats_band_background";
  ALTER TABLE "_pages_v_blocks_aamle_education" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_aamle_education" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_aamle_education_background";
  CREATE TYPE "public"."enum__pages_v_blocks_aamle_education_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_aamle_education" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_aamle_education_background";
  ALTER TABLE "_pages_v_blocks_aamle_education" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_aamle_education_background" USING "background"::"public"."enum__pages_v_blocks_aamle_education_background";
  ALTER TABLE "_pages_v_blocks_split_feature" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_split_feature" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_split_feature_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_split_feature" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_split_feature_text_colour";
  ALTER TABLE "_pages_v_blocks_split_feature" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_split_feature_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_split_feature_text_colour";
  ALTER TABLE "_pages_v_blocks_split_feature" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_split_feature" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_split_feature_background";
  CREATE TYPE "public"."enum__pages_v_blocks_split_feature_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_split_feature" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_split_feature_background";
  ALTER TABLE "_pages_v_blocks_split_feature" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_split_feature_background" USING "background"::"public"."enum__pages_v_blocks_split_feature_background";
  ALTER TABLE "_pages_v_blocks_tabs" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_tabs" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_tabs_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_tabs_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_tabs" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_tabs_text_colour";
  ALTER TABLE "_pages_v_blocks_tabs" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_tabs_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_tabs_text_colour";
  ALTER TABLE "_pages_v_blocks_tabs" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_tabs" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_tabs_background";
  CREATE TYPE "public"."enum__pages_v_blocks_tabs_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_tabs" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_tabs_background";
  ALTER TABLE "_pages_v_blocks_tabs" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_tabs_background" USING "background"::"public"."enum__pages_v_blocks_tabs_background";
  ALTER TABLE "_pages_v_blocks_contact_details" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_contact_details" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_contact_details_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_contact_details" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_contact_details_text_colour";
  ALTER TABLE "_pages_v_blocks_contact_details" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_contact_details_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_contact_details_text_colour";
  ALTER TABLE "_pages_v_blocks_icon_list" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_icon_list" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_icon_list_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_icon_list" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_icon_list_text_colour";
  ALTER TABLE "_pages_v_blocks_icon_list" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_icon_list_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_icon_list_text_colour";
  ALTER TABLE "_pages_v_blocks_map_embed" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_map_embed" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_map_embed_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_map_embed" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_map_embed_text_colour";
  ALTER TABLE "_pages_v_blocks_map_embed" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_map_embed_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_map_embed_text_colour";
  ALTER TABLE "_pages_v_blocks_leadership_spotlight" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_leadership_spotlight" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_leadership_spotlight" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_leadership_spotlight_text_colour";
  ALTER TABLE "_pages_v_blocks_leadership_spotlight" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_leadership_spotlight_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_leadership_spotlight_text_colour";
  ALTER TABLE "_pages_v_blocks_leadership_spotlight" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_leadership_spotlight" ALTER COLUMN "background" SET DEFAULT 'muted'::text;
  DROP TYPE "public"."enum__pages_v_blocks_leadership_spotlight_background";
  CREATE TYPE "public"."enum__pages_v_blocks_leadership_spotlight_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_leadership_spotlight" ALTER COLUMN "background" SET DEFAULT 'muted'::"public"."enum__pages_v_blocks_leadership_spotlight_background";
  ALTER TABLE "_pages_v_blocks_leadership_spotlight" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_leadership_spotlight_background" USING "background"::"public"."enum__pages_v_blocks_leadership_spotlight_background";
  ALTER TABLE "_pages_v_blocks_video_embed" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_video_embed" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_video_embed_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_video_embed" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_video_embed_text_colour";
  ALTER TABLE "_pages_v_blocks_video_embed" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_video_embed_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_video_embed_text_colour";
  ALTER TABLE "_pages_v_blocks_video_embed" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_video_embed" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_video_embed_background";
  CREATE TYPE "public"."enum__pages_v_blocks_video_embed_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_video_embed" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_video_embed_background";
  ALTER TABLE "_pages_v_blocks_video_embed" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_video_embed_background" USING "background"::"public"."enum__pages_v_blocks_video_embed_background";
  ALTER TABLE "_pages_v_blocks_try_booking" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_try_booking" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_try_booking_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_try_booking" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_try_booking_text_colour";
  ALTER TABLE "_pages_v_blocks_try_booking" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_try_booking_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_try_booking_text_colour";
  ALTER TABLE "_pages_v_blocks_try_booking" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_try_booking" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_try_booking_background";
  CREATE TYPE "public"."enum__pages_v_blocks_try_booking_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_try_booking" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_try_booking_background";
  ALTER TABLE "_pages_v_blocks_try_booking" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_try_booking_background" USING "background"::"public"."enum__pages_v_blocks_try_booking_background";
  ALTER TABLE "_pages_v_blocks_section" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_section" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_section_background";
  CREATE TYPE "public"."enum__pages_v_blocks_section_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_section" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_section_background";
  ALTER TABLE "_pages_v_blocks_section" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_section_background" USING "background"::"public"."enum__pages_v_blocks_section_background";
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_archive_background";
  CREATE TYPE "public"."enum__pages_v_blocks_archive_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_archive_background";
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_archive_background" USING "background"::"public"."enum__pages_v_blocks_archive_background";
  ALTER TABLE "_pages_v_blocks_specialist_directory" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_specialist_directory" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_specialist_directory" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_specialist_directory_text_colour";
  ALTER TABLE "_pages_v_blocks_specialist_directory" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_specialist_directory_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_specialist_directory_text_colour";
  ALTER TABLE "_pages_v_blocks_specialist_directory" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_specialist_directory" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_specialist_directory_background";
  CREATE TYPE "public"."enum__pages_v_blocks_specialist_directory_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_specialist_directory" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_specialist_directory_background";
  ALTER TABLE "_pages_v_blocks_specialist_directory" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_specialist_directory_background" USING "background"::"public"."enum__pages_v_blocks_specialist_directory_background";
  ALTER TABLE "_pages_v_blocks_specialty_directory" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_specialty_directory" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_specialty_directory" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_specialty_directory_text_colour";
  ALTER TABLE "_pages_v_blocks_specialty_directory" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_specialty_directory_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_specialty_directory_text_colour";
  ALTER TABLE "_pages_v_blocks_specialty_directory" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_specialty_directory" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_specialty_directory_background";
  CREATE TYPE "public"."enum__pages_v_blocks_specialty_directory_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_specialty_directory" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_specialty_directory_background";
  ALTER TABLE "_pages_v_blocks_specialty_directory" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_specialty_directory_background" USING "background"::"public"."enum__pages_v_blocks_specialty_directory_background";
  ALTER TABLE "_pages_v_blocks_resources_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_resources_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_resources_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_resources_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_resources_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_resources_grid_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_resources_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_resources_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_resources_grid" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_resources_grid_background";
  CREATE TYPE "public"."enum__pages_v_blocks_resources_grid_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_resources_grid" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_resources_grid_background";
  ALTER TABLE "_pages_v_blocks_resources_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_resources_grid_background" USING "background"::"public"."enum__pages_v_blocks_resources_grid_background";
  ALTER TABLE "_appt_guide_v" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_appt_guide_v" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__appt_guide_v_text_colour";
  CREATE TYPE "public"."enum__appt_guide_v_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_appt_guide_v" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__appt_guide_v_text_colour";
  ALTER TABLE "_appt_guide_v" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__appt_guide_v_text_colour" USING "text_colour"::"public"."enum__appt_guide_v_text_colour";
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "background" SET DEFAULT 'dark'::text;
  DROP TYPE "public"."enum__pages_v_blocks_mission_pillars_background";
  CREATE TYPE "public"."enum__pages_v_blocks_mission_pillars_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "background" SET DEFAULT 'dark'::"public"."enum__pages_v_blocks_mission_pillars_background";
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_mission_pillars_background" USING "background"::"public"."enum__pages_v_blocks_mission_pillars_background";
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_mission_pillars_text_colour";
  ALTER TABLE "_pages_v_blocks_mission_pillars" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_mission_pillars_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_mission_pillars_text_colour";
  ALTER TABLE "_pages_v_blocks_value_cards" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_value_cards" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_value_cards_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_value_cards" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_value_cards_text_colour";
  ALTER TABLE "_pages_v_blocks_value_cards" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_value_cards_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_value_cards_text_colour";
  ALTER TABLE "_pages_v_blocks_value_cards" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_value_cards" ALTER COLUMN "background" SET DEFAULT 'dark'::text;
  DROP TYPE "public"."enum__pages_v_blocks_value_cards_background";
  CREATE TYPE "public"."enum__pages_v_blocks_value_cards_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_value_cards" ALTER COLUMN "background" SET DEFAULT 'dark'::"public"."enum__pages_v_blocks_value_cards_background";
  ALTER TABLE "_pages_v_blocks_value_cards" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_value_cards_background" USING "background"::"public"."enum__pages_v_blocks_value_cards_background";
  ALTER TABLE "_pages_v_blocks_why_verify" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_why_verify" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_why_verify_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_why_verify" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_why_verify_text_colour";
  ALTER TABLE "_pages_v_blocks_why_verify" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_why_verify_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_why_verify_text_colour";
  ALTER TABLE "_pages_v_blocks_audience_pathways" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_audience_pathways" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_audience_pathways" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_audience_pathways_text_colour";
  ALTER TABLE "_pages_v_blocks_audience_pathways" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_audience_pathways_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_audience_pathways_text_colour";
  ALTER TABLE "_pages_v_blocks_audience_pathways" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_audience_pathways" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_audience_pathways_background";
  CREATE TYPE "public"."enum__pages_v_blocks_audience_pathways_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_audience_pathways" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_audience_pathways_background";
  ALTER TABLE "_pages_v_blocks_audience_pathways" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_audience_pathways_background" USING "background"::"public"."enum__pages_v_blocks_audience_pathways_background";
  ALTER TABLE "_pages_v_blocks_cost_grid" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cost_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_cost_grid" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_cost_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_cost_grid" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_cost_grid_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_cost_grid_text_colour";
  ALTER TABLE "_pages_v_blocks_featured_articles" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_featured_articles" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_featured_articles_background";
  CREATE TYPE "public"."enum__pages_v_blocks_featured_articles_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_featured_articles" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_featured_articles_background";
  ALTER TABLE "_pages_v_blocks_featured_articles" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_featured_articles_background" USING "background"::"public"."enum__pages_v_blocks_featured_articles_background";
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "text_colour" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::text;
  DROP TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour";
  CREATE TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" AS ENUM('inherit', 'brand', 'deep', 'bright', 'muted', 'white', 'heading', 'body');
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "text_colour" SET DEFAULT 'inherit'::"public"."enum__pages_v_blocks_events_explorer_text_colour";
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "text_colour" SET DATA TYPE "public"."enum__pages_v_blocks_events_explorer_text_colour" USING "text_colour"::"public"."enum__pages_v_blocks_events_explorer_text_colour";
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "separator_past_background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "separator_past_background" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum__pages_v_blocks_events_explorer_separator_past_background";
  CREATE TYPE "public"."enum__pages_v_blocks_events_explorer_separator_past_background" AS ENUM('default', 'white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "separator_past_background" SET DEFAULT 'default'::"public"."enum__pages_v_blocks_events_explorer_separator_past_background";
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "separator_past_background" SET DATA TYPE "public"."enum__pages_v_blocks_events_explorer_separator_past_background" USING "separator_past_background"::"public"."enum__pages_v_blocks_events_explorer_separator_past_background";
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "background" SET DEFAULT 'white'::text;
  DROP TYPE "public"."enum__pages_v_blocks_events_explorer_background";
  CREATE TYPE "public"."enum__pages_v_blocks_events_explorer_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "background" SET DEFAULT 'white'::"public"."enum__pages_v_blocks_events_explorer_background";
  ALTER TABLE "_pages_v_blocks_events_explorer" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_events_explorer_background" USING "background"::"public"."enum__pages_v_blocks_events_explorer_background";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_hero_background" SET DATA TYPE text;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_hero_background" SET DEFAULT 'accent-solid'::text;
  DROP TYPE "public"."enum__pages_v_version_hero_hero_background";
  CREATE TYPE "public"."enum__pages_v_version_hero_hero_background" AS ENUM('white', 'muted', 'accent', 'accent-solid', 'light', 'primary', 'dark');
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_hero_background" SET DEFAULT 'accent-solid'::"public"."enum__pages_v_version_hero_hero_background";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_hero_background" SET DATA TYPE "public"."enum__pages_v_version_hero_hero_background" USING "version_hero_hero_background"::"public"."enum__pages_v_version_hero_hero_background";
  ALTER TABLE "specialists" DROP COLUMN "profile_photo_shape";
  ALTER TABLE "_specialists_v" DROP COLUMN "version_profile_photo_shape";
  ALTER TABLE "team" DROP COLUMN "profile_photo_shape";
  ALTER TABLE "_team_v" DROP COLUMN "version_profile_photo_shape";
  ALTER TABLE "site_settings" DROP COLUMN "colors_ink_black";
  ALTER TABLE "site_settings" DROP COLUMN "colors_ink_charcoal";
  ALTER TABLE "site_settings" DROP COLUMN "colors_ink_grey";
  DROP TYPE "public"."enum_specialists_profile_photo_shape";
  DROP TYPE "public"."enum__specialists_v_version_profile_photo_shape";
  DROP TYPE "public"."enum_team_profile_photo_shape";
  DROP TYPE "public"."enum__team_v_version_profile_photo_shape";`)
}
